### PR TITLE
Create GithubNClone.ipynb

### PR DESCRIPTION
**Pull request by thefirehacker**
NoteBook Focus on Cloning a repo from github and then using Python File in rep as import in  Notebook.

Debugging Covered using PDB( Standard Python Debugger) and PixieDust

### CODE REVIEW

**Review by tirthshah20 — APPROVED** [review]
Notebook Looks good.

**Review by mewadashreya — APPROVED** [review]
nice work....

**Review by mewadashreya — APPROVED** [review]
nice work keep it up!!!

**Review by tirthshah20 — APPROVED** [review]
good work.

**Review by mewadashreya — APPROVED** [review]
looks good !!!

**Review by tirthshah20 — APPROVED** [review]
good one

**Pull request merged**
